// Shim: canonical domain types live in ./game/types (one file per concern).
// UI keeps importing from '../types' / './types' unchanged.
export type {
  CharacterClass,
  HunterState,
  Hunter,
  Monster,
  MonsterType,
  ZoneId,
  Building,
  BuildingType,
  MaterialType,
  MaterialStock,
  EquipmentRarity,
  EquipmentEffectId,
  Equipment,
  Skill,
  SkillEffectType,
  ActiveZone,
  ZoneKind,
  ItemDrop,
  FloatingText,
  SkillVFX,
  GameLog,
} from './game/types';
